<?php

namespace Jenyak\I18nRouting;

use Silex\RedirectableUrlMatcher as BaseUrlMatcher;
use Jenyak\I18nRouting\I18nControllerCollection;

/**
* I18nUrlMatcher
*
* Override the match method to return the original route name, not the one generated by the I18nUrlGenerator
*/
class I18nUrlMatcher extends BaseUrlMatcher
{
    public function match($pathinfo)
    {
        $parameters = parent::match($pathinfo);
        if (false !== $pos = strpos($parameters['_route'], I18nControllerCollection::ROUTING_PREFIX)) {
            $parameters['_route'] = substr($parameters['_route'], $pos + strlen(I18nControllerCollection::ROUTING_PREFIX));
        }

        return $parameters;
    }
}
